export class CentroCostosModel {
    intIdCostCenter_ID:number;
    intIdProceccGrp_ID:number;
    intIdCCGrpArea_ID:number;
    intIdCCCategory_ID:number;
    intIdCompany_ID:number;
    intIdClase_ID:number;
    strCompany_Cod:string;
    strCostCenter_NO:string;
    strCostCenter_Name:string;
    strCostCenter_Desc:string;
    strCostCen_Father_NO:string;
    strCostCen_Father_Desc:string;
    blnCostCenter_Level:boolean;
    dtmStart_Date:Date;
    dtmEnd_Date:Date;
    strCateg_Cod:string;
    strCateg_Desc:string;
    strProcGrp_Cod:string;
    strProcGrp_Desc:string;
    strAreaGrp_Cod:string;
    strAreaGrp_Desc:string;
    strCodAcctDest_Debit:string;
    strAcctDest_Credit:string;

    strCreation_User:string;
    dtmCreation_Date:Date;
    strModified_User:string;
    dtmModified_Date:Date;
    chrStatus:string;
 }