export class CentroCostosModel {
    intIdCostCenter_ID:number;
    intIdCCGrpArea_ID:number;
    intCCCategory_ID:number;
    intIdProccGrp_ID:number;
    strCompany_Cod:string;
    strCompany_Desc:string;
    strCostCenter_NO:string;
    strCostCenter_Name:string;
    strCostCenter_Desc:string;
    strlevel:string;
    strCostCen_Father_NO:string;
    strCostCen_Father_Desc:string;
    blnCostCenter_Level:boolean;
    dtmStart_Date:Date;
    dtmEnd_Date:Date;
    strCCCategory_Cod:string;
    strCCCategory_Desc:string;
    strCCGrpProc_Desc:string;
    strCCGrpArea_Cod:string;
    strCCGrpArea_Desc:string;
    strCodAcctDest_Debit:string;
    strAcctDest_Credit:string;
    strCCGrpProc_Cod:string;

    strCreation_User:string;
    dtmCreation_Date:Date;
    strModified_User:string;
    dtmModified_Date:Date;
    chrStatus:string;
    constructor(){
        this.intIdCostCenter_ID=-1;
        this.intIdCCGrpArea_ID=-1;
        this.intCCCategory_ID=-1;
        this.intIdProccGrp_ID=-1;
        this.strCompany_Cod='';
        this.strCompany_Desc='';
        this.strCostCenter_NO='';
        this.strCostCenter_Desc='';
        this.strCostCenter_Name='';
        this.strlevel='';
        this.strCostCen_Father_NO='';
        this.strCostCen_Father_Desc='';
        this.blnCostCenter_Level=true;
        this.dtmStart_Date=new Date();
        this.dtmEnd_Date=new Date();
        this.strCCCategory_Cod='';
        this.strCCCategory_Desc='';
        this.strCCGrpProc_Cod='';
        this.strCCGrpProc_Desc='';
        this.strCCGrpArea_Cod='';
        this.strCCGrpArea_Desc='';
        this.strCodAcctDest_Debit='';
        this.strAcctDest_Credit='';
        this.strCCGrpProc_Cod='';
        this.strCCGrpArea_Cod='';
        this.strCreation_User='';
        this.strModified_User='';
        this.dtmCreation_Date=new Date();
        this.dtmModified_Date=new Date();
        this.chrStatus='';
    }
 }