export class ClaseMaterialModel {
    // intIdClaseMaterial:number;
    // strCodClaseMaterial:string;
    // strDescripcion:string;
    // strCodCuentaGastoCorporativo:string;
    // strCodCuentaGastoPeru:string;
    // strCodCuentaInventario:string;

    // strUsuarioCrea:string;
    // dtmFechaCrea:Date;
    // strUsuarioModif:string;
    // dtmFechaModif:Date;
    // chrEstado:string;
    chrStatus: string;
    dtmCreation_Date: Date;
    dtmModified_Date: Date;
    intIdMatClass_ID: number;
    strAcct_Corp: string;
    strAcct_Exp: string;
    strAcct_Loc: string;
    strCreation_User: string;
    strMatClass_Cod: string;
    strMatClass_Desc: string;
    strMatClass_Name: string;
    strModified_User: string;
    strExp_Cod_Loc:string;
    strExp_Desc_Loc:string;
    strCompany_Cod:string;
    strCompany_Desc:string;
    strStock_Type_Cod:string;
    strStock_Type_Desc:string;
    strExp_Cod_Corp:string;
    strExp_Cod_Corp_Desc:string;
    strRecep_Deb:string;
    strRecep_Deb_Desc:string;
    strRecep_Cred:string;
    strRecep_Cred_Desc:string;
    strInvoice_Deb:string;
    strInvoice_Deb_Desc:string;	
    strInvoice_Cred:string;
    strInvoice_Cred_Desc:string;
    strIssue_Deb:string;
    strIssue_Deb_Desc:string;
    strIssue_Cred:string;
    strIssue_Cred_Desc:string;
    strAcct_Loc_Desc:string;
    strAcct_Corp_Desc:string;
    strExp_Cod_Loc_Desc:string;
}