export class FacturaDetalleModel{
    intAPDocD_ID:number;//
    intAPDocH_ID:number;//
    strCompany_Cod:string;//
    strVoucher_NO:string;//
    strPO_NO:string;//
    strPO_Item_NO:string;//falta
    strUM:string;//
    intQuantity:number;//
    intUnit_Price:number;//
    strDesc_Item:string;//
    strAccount_Cod:string;//falta
    strCostCenter_NO:string;//falta
    strValue_Doc:string;//falta
    strValue_Local:string;
    strValue_Corp:string;
    strTax_Porcent:string;
    strWH_Detrac_Cod:string;
    strValue_WH_Detrac:string;
    strWH_Reten_Cod:string;
    strValue_WH_Retention:string;
    strCreation_User:string;
    dtmCreation_Date:Date;
    strModified_User:string;
    dtmModified_Date:Date;
    chrStatus:string;
}