
export class OrdenCompraDetalleModel {
    intAutoIncremental:number;
    intIdPODetalle:number;
    intIdProducto:number;
    intIdOrdenCompra:number; 
    intIdCategoriaCuenta:number;
    intIdCategoriaLinea:number;   
    intIdMoneda:number;   
    strCodCategoriaCuenta:string;
    strCodCategoriaLinea:string;
    strCodMoneda:string;
    strCodProducto:string;
    strCodAlmacen:string;
    intPO_ITEM_NO:number ;
    strPO_Item_Desc:string ;
    strRequisition_Number:string ;
    intRequisitio_Item:number ;
    intChange_Count:number ;
    chrReceipt_Status:number ;
    strMaterial_Group:string ;
    intIdCentroCosto:number ;
    strUnit_Of_Purch:string ;
    fltPO_QTY_I:number ;
    fltPO_Net_PR_I:number ;
    fltCurr_Net_PR_P:number ;
    intConv_Factor:number ;
    fltVal_Pen_USD:number ;
    fltVal_Pen_Local:number ;
    fltVal_Pen_Corp:number ;
    fltVal_Tot_PO_Item:number ;
    strTax_Cod:string ;
    strWH_Tax_Detraccion:string ;
    strWH_Retention:string ;
    fltTax_Percent:number ;
    intIdAlmacen:number ;
    intInv_QTY_UOP:number ;
    strInvoice_REF:number ;
    fltInv_Pend_QTY_P:number ;
    fltInv_Pend_Val_F:number ;
    fltInv_Pend_Val_L:number ;
    fltInv_Pend_Val_S:number ;
    strDeliv_Location:string ;
    strDescription:string ;
    strTot_PO_Item_Val:string ;
    strAccount_Code:string ;
    strUser_ID:string ;
    dtmCreation_Date:Date ;
    strModify_User:string ;
    dmModified_Date:Date ;
    chrStatus:string ;
    chrTipo:string;
    fltPorcent:number;
    strCurrency_Code:string;
    constructor(item: OrdenCompraDetalleModel = {} as OrdenCompraDetalleModel){
        this.strCurrency_Code=item.strCurrency_Code;
        this.chrTipo=item.chrTipo;
        this.fltPorcent=item.fltPorcent;
        this.intAutoIncremental=item.intAutoIncremental;
        this.intIdPODetalle=item.intIdPODetalle;
        this.intIdProducto=item.intIdProducto;
        this.intIdOrdenCompra=item.intIdOrdenCompra;
        this.intIdCategoriaCuenta=item.intIdCategoriaCuenta;
        this.intIdCategoriaLinea=item.intIdCategoriaLinea;
        this.intIdMoneda=item.intIdMoneda;
        this.strCodCategoriaCuenta=item.strCodCategoriaCuenta;
        this.strCodCategoriaLinea=item.strCodCategoriaLinea;
        this.strCodMoneda=item.strCodMoneda;
        this.strCodProducto=item.strCodProducto;
        this.strCodAlmacen=item.strCodAlmacen;
        this.intPO_ITEM_NO=item.intPO_ITEM_NO;
        this.strRequisition_Number=item.strRequisition_Number;
        this.intRequisitio_Item=item.intRequisitio_Item;
        this.intChange_Count=item.intChange_Count;
        this.chrReceipt_Status=item.chrReceipt_Status;
        this.strMaterial_Group=item.strMaterial_Group;
        this.intIdCentroCosto=item.intIdCentroCosto;
        this.strUnit_Of_Purch=item.strUnit_Of_Purch;
        this.fltPO_QTY_I=item.fltPO_QTY_I;
        this.fltPO_Net_PR_I=item.fltPO_Net_PR_I;
        this.fltCurr_Net_PR_P=item.fltCurr_Net_PR_P;
        this.intConv_Factor=item.intConv_Factor;
        this.fltVal_Pen_USD=item.fltVal_Pen_USD;
        this.fltVal_Pen_Local=item.fltVal_Pen_Local;
        this.fltVal_Pen_Corp=item.fltVal_Pen_Corp;
        this.fltVal_Tot_PO_Item=item.fltVal_Tot_PO_Item;
        this.strTax_Cod=item.strTax_Cod;
        this.strWH_Tax_Detraccion=item.strWH_Tax_Detraccion;
        this.strWH_Retention=item.strWH_Retention;
        this.fltTax_Percent=item.fltTax_Percent;
        this.intIdAlmacen=item.intIdAlmacen;
        this.intInv_QTY_UOP=item.intInv_QTY_UOP;
        this.strInvoice_REF=item.strInvoice_REF;
        this.fltInv_Pend_QTY_P=item.fltInv_Pend_QTY_P;
        this.fltInv_Pend_Val_F=item.fltInv_Pend_Val_F;
        this.fltInv_Pend_Val_L=item.fltInv_Pend_Val_L;
        this.fltInv_Pend_Val_S=item.fltInv_Pend_Val_S;
        this.strDeliv_Location=item.strDeliv_Location;
        this.strDescription=item.strDescription;
        this.strTot_PO_Item_Val=item.strTot_PO_Item_Val;
        this.strAccount_Code=item.strAccount_Code;
        this.strUser_ID=item.strUser_ID;
        this.dtmCreation_Date=item.dtmCreation_Date;
        this.strModify_User=item.strModify_User;
        this.dmModified_Date=item.dmModified_Date;
        this.chrStatus=item.chrStatus;
        this.strPO_Item_Desc=item.strPO_Item_Desc;
    }
}


