
export class ProductoModel {
    intIdInvStock_ID:number;
    intIdCritical_ID:number;
    intIdAcctCont_ID:number;
    intIdMatClass_ID:number;
    intIdGrpPurch_ID:number;
    intIdUnidadMedida:number;
    intIdWHS_Stat_ID:number;
    intIdCtlPrec_ID:number;
    intIdCategMat_ID:number;
    intIdCommTax_ID:number;
    intIdVendor_ID:number;
    strCompany_Cod:string;
    strStock_Cod:string;
    strWHS_Cod:string;
    strStock_Cod_Old:string;
    strStock_Name:string;
    strStock_Desc:string;
    fltPrecUnit_Local:number;
    fltPrecUnit_USD:number;
    strPart_NO:string;
    strStock_Type:string;
    strFleet:string;
    strExp_Acct:string;
    strMaterial_Class:string;
    strMaterial_Categ:string;
    strCritical_Item:string;
    strGrpPurch_Cod:string;
    strVendor_NO:string;
    strVendor_Desc:string;
    strWHS_Status:string;
    fltQtyLimit_Min:number;
    fltQtyLimit_Max:number;
    fltFactor:number;
    strTAX_Ind:string;
    fltQuantity:number;
    fltQuantity_Balance:number;
    strUM_Cod:string;
    fltActual_Local:number;
    fltActual_USD:number;
    fltPriceControl:number;

    strCreation_User:string;
    dtmCreation_Date:Date;
    strModified_User:string;
    dtmModified_Date:Date;
    chrStatus:string;
}
