import { environment } from "../environments/environment";

let basePath = environment.APIPath;

export const APIConstant = {
    basePath: basePath,
    sensorData: `${basePath}sensordata`,
    tv: `${basePath}tv`,
    light: `${basePath}light`,
    ac: `${basePath}ac`,
    heating: `${basePath}heating`,
    history: `${basePath}history`,
    restaurant: `${basePath}restaurant`,
    login: `${basePath}auth/signin`,
    register: `${basePath}auth/signup`,
    me: `${basePath}me`,
    user: `${basePath}producto`,
    changePassword: `${basePath}changepassword`,
    centrocosto:`${basePath}centrocosto`,
    moneda:`${basePath}moneda`,
    pais:`${basePath}pais`,
    banco:`${basePath}banco`,
    tipomediopago:`${basePath}mediopago`,
    tipodocidentidad:`${basePath}tipodocidentidad`,
    existencia:`${basePath}existencia`,
    unidadmedida:`${basePath}unidadmedida`,
    aduana:`${basePath}codigoaduana`,
    metodovaluacion:`${basePath}metodovaluacion`,
    plancuenta:`${basePath}plancuentas`,
    catalogoexistencia:`${basePath}catalogoexistencia`,
    tipooperacion:`${basePath}tipooperacion`,
    tipocomprobantepago:`${basePath}tipocomprobantepago`,
    compania:`${basePath}compania`,
    claseproducto:`${basePath}claseproducto`,    
    grupoproducto:`${basePath}grupoproducto`,    
    tipoproducto:`${basePath}tipoproducto`,
    tipotransaccion:`${basePath}tipotransaccion`,    
    grupocuentacontable:`${basePath}grupocuentacontable`,
    grupogastos:`${basePath}grupogastos`,
    rubro:`${basePath}rubro`,
    tipocuentacontable:`${basePath}tipocuentacontable`,
    impuesto:`${basePath}impuesto`,
    cuentacontable:`${basePath}cuentacontable`,
    plancuentacorporativo:`${basePath}plancuentacorporativo`,
    
    categoriacuenta:`${basePath}categoriacuenta`,
  
    categorialinea:`${basePath}categorialinea`,
    categoriacentrocosto:`${basePath}categoriacentrocosto`,
    grupoarea:`${basePath}grupoarea`,
    prioridad:`${basePath}prioridad`,
    almacen:`${basePath}almacen`,
    clasematerial:`${basePath}clasematerial`,
    grupocomprador:`${basePath}grupocomprador`,
    
    producto: `${basePath}producto`,
    estado: `${basePath}estado`,
    
    controlprecio: `${basePath}controlprecio`,
    categoriamaterial: `${basePath}categoriamaterial`,    
    impuestomercaderia: `${basePath}impuestomercaderia`,
    productoalm: `${basePath}productoalm`,
    sucursal: `${basePath}sucursal`,
    criticidad: `${basePath}criticidad`,
    requisicion:`${basePath}requisicion`,
    bancopagador:`${basePath}bancopagador`,
    ordencompra:`${basePath}ordencompra`,
    proveedor:`${basePath}proveedor`,
}
