
export const API_URL = 'http://pektyasrv814/PDPHSEC_SERVICE/api/';
// export const API_URL = 'http://localhost:59154/api/'
export const USUARIO_LOGED = 'vuetest';
export const Local_PathImage='http://pektyasrv814/PDPHSEC_SERVICE/Imagenes/FileImage/';
export const Local_PathPdf='http://pektyasrv814/PDPHSEC_SERVICE/Imagenes/Filepdf/';
export const Local_PathPdfNews='http://pektyasrv814/PDPHSEC_SERVICE/Imagenes/FilePdfNews/';
export const Local_PathPdfApproved='http://pektyasrv814/PDPHSEC_SERVICE/Imagenes/FilePdfApproved/';
export const Local_PathComparer='http://pektyasrv814/PDPHSEC_SERVICE/Imagenes/Comparater/';
export const Local_Image='http://pektyasrv814/PDPHSEC_SERVICE/Imagenes/plantilla/';
export const Local_PathTemporal='http://pektyasrv814/PDPHSEC_SERVICE/Imagenes/Temporalfile/';
export const Local_PathVersiones='http://pektyasrv814/PDPHSEC_SERVICE/Imagenes/Versiones/';
export const TOKEN_SECRET=process.env.TOKEN_SECRET || "tokenultrasecreto"
// export const API_URL = 'http://localhost:59154/api/';
// export const USUARIO_LOGED = 'vuetest';
// export const Local_PathImage='http://localhost/PDP_FastDoc/Imagenes/FileImage/';
// export const Local_PathPdf='http://localhost/PDP_FastDoc/Imagenes/Filepdf/';
// export const Local_PathImage='http://localhost/PDP_FastDoc/Imagenes/FileImage/';
// export const Local_PathPdf='http://localhost/PDP_FastDoc/Imagenes/Filepdf/';
// export const Local_PathPdfNews='http://localhost/PDP_FastDoc/Imagenes/FilePdfNews/';
// export const Local_PathPdfApproved='http://localhost/PDP_FastDoc/Imagenes/FilePdfApproved/';
// export const Local_PathComparer='http://localhost/PDP_FastDoc/Imagenes/Comparater/';
// export const Local_Image='http://localhost/PDP_FastDoc/Imagenes/plantilla/';